[project]
name = "pyspark-analysis-project"
version = "0.1.0"
description = "Data analysis project using PySpark and Docker."
requires-python = ">=3.10"

dependencies = [
    "pyspark == 4.0.0",
    "pandas>=2.0.0,<3.0.0",
]